export function renderHelp(): string {
  return [
    'goodvibes-agent',
    '',
    'Usage:',
    '  goodvibes-agent tui',
    '  goodvibes-agent config',
    '  goodvibes-agent status',
    '  goodvibes-agent auth',
    '  goodvibes-agent smoke',
    '  goodvibes-agent policy <request>',
    '  goodvibes-agent chat <message>',
    '  goodvibes-agent ask <knowledge query> [--json]',
    '  goodvibes-agent search <knowledge query> [--json]',
    '  goodvibes-agent remember <fact>',
    '  goodvibes-agent delegate [--wrfc] <build/fix/review task>',
    '  goodvibes-agent delegations [list|status <id>] [--json]',
    '  goodvibes-agent approvals [approve|deny|cancel <id> --yes] [--json]',
    '  goodvibes-agent workplan [--json]',
    '  goodvibes-agent automation [snapshot|jobs|runs|heartbeat|capacity|run|pause|resume|cancel|retry] [id] [--yes] [--json]',
    '  goodvibes-agent schedules [run <id> --yes] [--json]',
    '  goodvibes-agent memory [query]',
    '  goodvibes-agent memory add|update|review|stale|delete|search|list',
    '  goodvibes-agent skills create|update|review|stale|enable|disable|active|delete|search|list',
    '  goodvibes-agent personas create|update|review|stale|use|active|delete|search|list',
    '',
    'The default command is tui.',
  ].join('\n');
}
