export function renderHelp(): string {
  return [
    'goodvibes-agent',
    '',
    'Usage',
    '  goodvibes-agent [command]',
    '  goodvibes-agent tui',
    '',
    'Daemon and config',
    '  goodvibes-agent config',
    '  goodvibes-agent status',
    '  goodvibes-agent auth',
    '  goodvibes-agent smoke',
    '',
    'Assistant work',
    '  goodvibes-agent policy <request>',
    '  goodvibes-agent chat <message>',
    '  goodvibes-agent ask <knowledge query> [--json]',
    '  goodvibes-agent search <knowledge query> [--json]',
    '  goodvibes-agent workplan [--json]',
    '  goodvibes-agent approvals [--json]',
    '  goodvibes-agent automation [snapshot|jobs|runs|heartbeat|capacity|run|pause|resume|cancel|retry] [id] [--yes] [--json]',
    '  goodvibes-agent schedules [run <id> --yes] [--json]',
    '',
    'Local memory, skills, and personas',
    '  goodvibes-agent remember <fact>',
    '  goodvibes-agent memory [query]',
    '  goodvibes-agent memory add|update|review|stale|delete|search|list',
    '  goodvibes-agent skills create|update|review|stale|enable|disable|active|delete|search|list',
    '  goodvibes-agent personas create|update|review|stale|use|active|delete|search|list',
    '',
    'Delegation and explicit mutations',
    '  goodvibes-agent delegate [--wrfc] <build/fix/review task>',
    '  goodvibes-agent delegations [list|status <id>] [--json]',
    '  goodvibes-agent approvals approve|deny|cancel <id> --yes [--json]',
    '  goodvibes-agent automation run|pause|resume <job-id> --yes [--json]',
    '  goodvibes-agent automation cancel|retry <run-id> --yes [--json]',
    '  goodvibes-agent schedules run <schedule-id> --yes [--json]',
    '',
    'Safety',
    '  Normal chat uses companion.chat. Build work delegates to GoodVibes TUI.',
    '  Side-effecting operator routes require exact commands plus --yes.',
    '  WRFC is requested only when explicit build/fix/review work asks for it.',
    '',
    'The default command is tui.',
  ].join('\n');
}
