export function renderHelp(): string {
  return [
    'goodvibes-agent',
    '',
    'Usage:',
    '  goodvibes-agent tui',
    '  goodvibes-agent config',
    '  goodvibes-agent status',
    '  goodvibes-agent auth',
    '  goodvibes-agent smoke',
    '  goodvibes-agent chat <message>',
    '  goodvibes-agent ask <knowledge query> [--json]',
    '  goodvibes-agent search <knowledge query> [--json]',
    '  goodvibes-agent remember <fact>',
    '  goodvibes-agent delegate [--wrfc] <build/fix/review task>',
    '  goodvibes-agent delegations [list|status <id>] [--json]',
    '  goodvibes-agent approvals [--json]',
    '  goodvibes-agent workplan [--json]',
    '  goodvibes-agent memory [query]',
    '  goodvibes-agent memory add|update|review|stale|delete|search|list',
    '  goodvibes-agent skills create|update|review|delete|search|list',
    '  goodvibes-agent personas create|update|review|delete|search|list',
    '',
    'The default command is tui.',
  ].join('\n');
}
