import type { AgentWorkspaceCategory } from './agent-workspace-types.ts';

export const AGENT_WORKSPACE_CATEGORIES: readonly AgentWorkspaceCategory[] = [
  {
    id: 'home',
    group: 'OPERATE',
    label: 'Home',
    summary: 'Main operator workspace for normal assistant work.',
    detail: 'Use this as the Agent front door: chat in the main conversation, inspect state, choose model/provider, and open setup without switching modes.',
    actions: [
      { id: 'chat', label: 'Continue assistant chat', detail: 'Return to the main composer and type a normal message. Agent work stays serial in the main conversation.', kind: 'guidance', safety: 'safe' },
      { id: 'brief', label: 'Operator briefing', detail: 'Show a concise Agent status and next-actions briefing without mutating the connected host.', command: '/brief', kind: 'command', safety: 'read-only' },
      { id: 'model', label: 'Choose model', detail: 'Open the model/provider workspace for the Agent chat route.', command: '/model', kind: 'command', safety: 'safe' },
      { id: 'mode-show', label: 'Interaction mode', detail: 'Review Agent interaction noise level and per-domain verbosity.', command: '/mode show', kind: 'command', safety: 'read-only' },
      { id: 'mode-preset', label: 'Set interaction mode', detail: 'Open a confirmed form for quiet, balanced, or operator interaction mode.', editorKind: 'mode-preset', kind: 'editor', safety: 'safe' },
      { id: 'setup-home', label: 'Setup checklist', detail: 'Jump to the first-run checklist for provider, knowledge, personas, skills, routines, memory, channels, and voice/media.', targetCategoryId: 'setup', kind: 'workspace', safety: 'safe' },
      { id: 'knowledge-home', label: 'Agent Knowledge', detail: 'Jump to isolated Agent Knowledge status, ingest, search, and review flows.', targetCategoryId: 'knowledge', kind: 'workspace', safety: 'read-only' },
      { id: 'memory-home', label: 'Memory, skills, routines', detail: 'Jump to local memory, persona, skill, and routine setup. These are core Agent product features.', targetCategoryId: 'memory', kind: 'workspace', safety: 'safe' },
      { id: 'learned-behavior-home', label: 'Capture learned behavior', detail: 'Save a reviewed lesson, workflow, or operating style as a local skill, routine, or persona.', editorKind: 'learned-behavior', kind: 'editor', safety: 'safe' },
      { id: 'channels-home', label: 'Channels', detail: 'Jump to companion pairing and channel readiness without changing connected-host routing.', targetCategoryId: 'channels', kind: 'workspace', safety: 'read-only' },
      { id: 'tools-home', label: 'Tools and MCP', detail: 'Jump to MCP server setup, tool inventory, and trust review for day-one operator tool use.', targetCategoryId: 'tools', kind: 'workspace', safety: 'safe' },
      { id: 'voice-home', label: 'Voice and media', detail: 'Jump to voice, TTS, image input, browser-tool, and media setup.', targetCategoryId: 'voice-media', kind: 'workspace', safety: 'safe' },
      { id: 'help', label: 'Browse commands', detail: 'Open registry-driven command help.', command: '/help', kind: 'command', safety: 'safe' },
      { id: 'health', label: 'Review health', detail: 'Show local health and connected-host status without starting or mutating anything.', command: '/health review', kind: 'command', safety: 'read-only' },
    ],
  },
  {
    id: 'setup',
    group: 'SETUP',
    label: 'Setup',
    summary: 'Configuration, auth, provider, and onboarding workspaces.',
    detail: 'Use this to configure the assistant: provider/model, setup checklist, Agent Knowledge, local behavior, channels, and voice/media. Changes here stay Agent-owned.',
    actions: [
      { id: 'config', label: 'Open settings', detail: 'Open the fullscreen Agent settings workspace.', command: '/config', kind: 'command', safety: 'safe' },
      { id: 'setup', label: 'Run setup', detail: 'Review Agent settings in the fullscreen setup flow.', command: '/setup', kind: 'command', safety: 'safe' },
      { id: 'setup-provider-model', label: 'Provider and model', detail: 'Choose the provider/model route for normal assistant chat.', command: '/model', kind: 'command', safety: 'safe' },
      { id: 'setup-model-pinned', label: 'Pinned models', detail: 'Inspect model favorites from the Agent TUI before changing model selection.', command: '/pin', kind: 'command', safety: 'read-only' },
      { id: 'setup-model-refresh', label: 'Refresh model catalog', detail: 'Refresh model catalog, benchmark, and token-limit metadata from the Agent TUI.', command: '/refresh-models', kind: 'command', safety: 'safe' },
      { id: 'setup-model-pin', label: 'Pin model', detail: 'Open a form that pins one model registry key for quick reuse.', editorKind: 'model-pin', kind: 'editor', safety: 'safe' },
      { id: 'setup-model-unpin', label: 'Unpin model', detail: 'Open a form that removes one pinned model registry key.', editorKind: 'model-unpin', kind: 'editor', safety: 'safe' },
      { id: 'setup-mode-show', label: 'Interaction mode', detail: 'Review current Agent interaction mode and domain verbosity.', command: '/mode show', kind: 'command', safety: 'read-only' },
      { id: 'setup-mode-preset', label: 'Set interaction mode', detail: 'Open a confirmed form for quiet, balanced, or operator interaction mode.', editorKind: 'mode-preset', kind: 'editor', safety: 'safe' },
      { id: 'setup-mode-domain', label: 'Set domain verbosity', detail: 'Open a confirmed form for one interaction-domain verbosity override.', editorKind: 'mode-domain', kind: 'editor', safety: 'safe' },
      { id: 'setup-compat', label: 'Compatibility', detail: 'Inspect Agent SDK pin, connected host version, and isolated Agent Knowledge route readiness.', command: '/compat', kind: 'command', safety: 'read-only' },
      { id: 'setup-agent-knowledge', label: 'Agent Knowledge', detail: 'Inspect the isolated Agent Knowledge store before ingesting source-backed material.', command: '/knowledge status', kind: 'command', safety: 'read-only' },
      { id: 'setup-runtime-profiles', label: 'Agent profiles', detail: 'Browse starter templates for isolated Agent homes and operator identities.', command: '/agent-profile templates', kind: 'command', safety: 'read-only' },
      { id: 'setup-profile-from-discovered', label: 'Profile from discovered behavior', detail: 'Create an isolated Agent profile directly from reviewed local persona, skill, and routine files.', editorKind: 'profile-from-discovered', kind: 'editor', safety: 'safe' },
      { id: 'support-bundle-export', label: 'Export support bundle', detail: 'Open a confirmed form that exports a redacted Agent support bundle from the TUI workspace.', editorKind: 'support-bundle-export', kind: 'editor', safety: 'safe' },
      { id: 'support-bundle-inspect', label: 'Inspect support bundle', detail: 'Open a form that inspects a redacted Agent support bundle before import or sharing.', editorKind: 'support-bundle-inspect', kind: 'editor', safety: 'read-only' },
      { id: 'support-bundle-import', label: 'Import support bundle', detail: 'Open a confirmed form that imports reviewed, non-redacted config values from an Agent support bundle.', editorKind: 'support-bundle-import', kind: 'editor', safety: 'safe' },
      { id: 'setup-personas', label: 'Personas', detail: 'Create or select the active local Agent persona.', targetCategoryId: 'personas', kind: 'workspace', safety: 'safe' },
      { id: 'setup-skills', label: 'Skills', detail: 'Create, review, and enable reusable local Agent skills.', targetCategoryId: 'skills', kind: 'workspace', safety: 'safe' },
      { id: 'setup-routines', label: 'Routines', detail: 'Create, review, and enable local Agent routines before any explicit schedule promotion.', targetCategoryId: 'routines', kind: 'workspace', safety: 'safe' },
      { id: 'setup-memory', label: 'Local memory', detail: 'Inspect Agent-local memory; secrets stay rejected or redacted.', command: '/memory', kind: 'command', safety: 'read-only' },
      { id: 'setup-channels', label: 'Channels', detail: 'Open companion pairing and channel readiness setup.', command: '/pair', kind: 'command', safety: 'safe' },
      { id: 'setup-tools', label: 'Tools and MCP', detail: 'Open MCP setup, trust review, and tool inventory.', targetCategoryId: 'tools', kind: 'workspace', safety: 'safe' },
      { id: 'setup-voice-media', label: 'Voice and media', detail: 'Open TTS/media settings for voice and image-capable Agent flows.', command: '/config tts', kind: 'command', safety: 'safe' },
      { id: 'provider', label: 'Provider status', detail: 'Review provider/model posture.', command: '/provider', kind: 'command', safety: 'read-only' },
      { id: 'provider-use', label: 'Use provider', detail: 'Open a provider-id form that switches the Agent chat provider from the workspace.', editorKind: 'provider-use', kind: 'editor', safety: 'safe' },
      { id: 'provider-inspect', label: 'Inspect provider', detail: 'Open a provider-id form for read-only provider auth/setup inspection.', editorKind: 'provider-inspect', kind: 'editor', safety: 'read-only' },
      { id: 'provider-add', label: 'Add custom provider', detail: 'Open a confirmed form that adds one OpenAI-compatible custom provider for Agent model routing.', editorKind: 'provider-add', kind: 'editor', safety: 'safe' },
      { id: 'provider-remove', label: 'Remove custom provider', detail: 'Open a confirmed form that removes one Agent custom provider config.', editorKind: 'provider-remove', kind: 'editor', safety: 'safe' },
      { id: 'provider-accounts', label: 'Provider accounts', detail: 'Review provider account routes, subscription windows, and billing-path safety without starting login or repair flows.', command: '/accounts review', kind: 'command', safety: 'read-only' },
      { id: 'subscription-providers', label: 'Subscription providers', detail: 'Review provider subscription login routes without starting a login.', command: '/subscription providers', kind: 'command', safety: 'read-only' },
      { id: 'subscription-review', label: 'Subscription review', detail: 'Inspect active and pending provider subscription sessions without printing token values.', command: '/subscription review', kind: 'command', safety: 'read-only' },
      { id: 'subscription-inspect', label: 'Inspect subscription provider', detail: 'Open a provider-id form for read-only OAuth/subscription route inspection.', editorKind: 'subscription-inspect', kind: 'editor', safety: 'read-only' },
      { id: 'subscription-login-start', label: 'Start subscription login', detail: 'Open a confirmed form for one provider OAuth login start, with browser/manual callback controls.', editorKind: 'subscription-login-start', kind: 'editor', safety: 'safe' },
      { id: 'subscription-login-finish', label: 'Finish subscription login', detail: 'Open a confirmed form that stores one completed provider subscription session from a code or redirect URL.', editorKind: 'subscription-login-finish', kind: 'editor', safety: 'safe' },
      { id: 'subscription-logout', label: 'Logout subscription', detail: 'Open a confirmed form that removes one stored provider subscription session.', editorKind: 'subscription-logout', kind: 'editor', safety: 'safe' },
      { id: 'subscription-bundle-export', label: 'Export subscription bundle', detail: 'Open a confirmed form that exports a redacted provider subscription bundle for setup review.', editorKind: 'subscription-bundle-export', kind: 'editor', safety: 'safe' },
      { id: 'subscription-bundle-inspect', label: 'Inspect subscription bundle', detail: 'Open a form that inspects a provider subscription bundle before setup review.', editorKind: 'subscription-bundle-inspect', kind: 'editor', safety: 'read-only' },
      { id: 'auth', label: 'Auth review', detail: 'Review authentication posture without printing token values.', command: '/auth review', kind: 'command', safety: 'read-only' },
      { id: 'auth-show', label: 'Inspect provider auth', detail: 'Open a provider-id form for read-only provider auth inspection.', editorKind: 'auth-show', kind: 'editor', safety: 'read-only' },
      { id: 'auth-repair', label: 'Auth repair guidance', detail: 'Open a provider-id form that shows auth repair guidance without storing tokens or starting login.', editorKind: 'auth-repair', kind: 'editor', safety: 'read-only' },
      { id: 'auth-bundle-export', label: 'Export auth bundle', detail: 'Open a confirmed form that exports a redacted auth review bundle.', editorKind: 'auth-bundle-export', kind: 'editor', safety: 'safe' },
      { id: 'auth-bundle-inspect', label: 'Inspect auth bundle', detail: 'Open a form that inspects an auth review bundle before setup review.', editorKind: 'auth-bundle-inspect', kind: 'editor', safety: 'read-only' },
    ],
  },
  {
    id: 'channels',
    group: 'SETUP',
    label: 'Channels',
    summary: 'Companion pairing, channel posture, and delivery safety.',
    detail: 'Agent uses connected channel accounts. Pairing, account inspection, and readiness checks are visible here; inbound delivery and public channel exposure stay policy-gated.',
    actions: [
      { id: 'pair', label: 'Pair companion', detail: 'Open the QR pairing view for companion app setup.', command: '/pair', kind: 'command', safety: 'safe' },
      { id: 'channel-readiness', label: 'Channel readiness', detail: 'Show the read-only readiness matrix.', command: '/channels', kind: 'command', safety: 'read-only' },
      { id: 'channel-attention', label: 'Needs attention', detail: 'Show enabled channels that still need setup or a delivery target.', command: '/channels attention', kind: 'command', safety: 'read-only' },
      { id: 'channel-accounts', label: 'Channel accounts', detail: 'Inspect connected channel accounts without printing secret values or sending messages.', command: '/channels accounts', kind: 'command', safety: 'read-only' },
      { id: 'channel-policies', label: 'Channel policies', detail: 'Inspect channel delivery policy posture without changing routing.', command: '/channels policies', kind: 'command', safety: 'read-only' },
      { id: 'channel-status', label: 'Live channel status', detail: 'Inspect channel runtime status from the connected host without mutating state.', command: '/channels status', kind: 'command', safety: 'read-only' },
      { id: 'channel-show', label: 'Show channel detail', detail: 'Open a channel-id form for read-only readiness details.', editorKind: 'channel-show', kind: 'editor', safety: 'read-only' },
      { id: 'channel-doctor', label: 'Run channel doctor', detail: 'Open a channel-id form for read-only route diagnostics.', editorKind: 'channel-doctor', kind: 'editor', safety: 'read-only' },
      { id: 'channel-setup', label: 'Setup guidance', detail: 'Open a channel-id form for read-only setup guidance.', editorKind: 'channel-setup', kind: 'editor', safety: 'read-only' },
      { id: 'notification-routes', label: 'Notification routes', detail: 'Inspect configured webhook notification URLs without sending a test message.', command: '/notify list', kind: 'command', safety: 'read-only' },
      { id: 'notification-add-webhook', label: 'Add webhook target', detail: 'Open a confirmed form that adds one webhook notification target for explicit reminder and routine delivery.', editorKind: 'notify-webhook', kind: 'editor', safety: 'safe' },
      { id: 'notification-remove-webhook', label: 'Remove webhook target', detail: 'Open a confirmed form that removes one exact webhook notification target from Agent delivery.', editorKind: 'notify-webhook-remove', kind: 'editor', safety: 'safe' },
      { id: 'notification-clear-webhooks', label: 'Clear webhook targets', detail: 'Open a confirmed form before removing every configured webhook notification target.', editorKind: 'notify-webhook-clear', kind: 'editor', safety: 'safe' },
      { id: 'notification-test-webhooks', label: 'Test webhook targets', detail: 'Open a confirmed form that sends one notification test to configured webhook targets only after typed confirmation.', editorKind: 'notify-webhook-test', kind: 'editor', safety: 'safe' },
      { id: 'setup-review', label: 'Health review', detail: 'Review setup posture without changing inbound delivery or mutating channel state.', command: '/health review', kind: 'command', safety: 'read-only' },
      { id: 'channel-safety', label: 'Delivery safety', detail: 'External messages, channel DMs, and public delivery targets require explicit user action and Agent policy. Agent will not silently send or expose channels from this workspace.', kind: 'guidance', safety: 'blocked' },
    ],
  },
  {
    id: 'tools',
    group: 'SETUP',
    label: 'Tools & MCP',
    summary: 'MCP server setup, trust review, and tool inventory.',
    detail: 'Configure and inspect task tools from the Agent TUI. Adding or changing tools requires typed confirmation; normal chat still chooses tools serially in the main conversation.',
    actions: [
      { id: 'mcp-workspace', label: 'Open MCP workspace', detail: 'Open the fullscreen MCP server and tool workspace with live server status, tool list, config paths, and confirmed add/remove/reload actions.', command: '/mcp', kind: 'command', safety: 'safe' },
      { id: 'mcp-review', label: 'MCP review', detail: 'Inspect MCP server connection, trust, role, and quarantine posture.', command: '/mcp review', kind: 'command', safety: 'read-only' },
      { id: 'mcp-tools', label: 'Tool inventory', detail: 'List available MCP tools grouped by server.', command: '/mcp tools', kind: 'command', safety: 'read-only' },
      { id: 'mcp-config', label: 'Config locations', detail: 'Show effective MCP config locations and source scopes without mutating them.', command: '/mcp config', kind: 'command', safety: 'read-only' },
      { id: 'mcp-add-server', label: 'Add MCP server', detail: 'Open a confirmed form that adds or updates one MCP server config with scope, role, trust, env refs, paths, and hosts.', editorKind: 'mcp-server', kind: 'editor', safety: 'safe' },
      { id: 'mcp-auth-review', label: 'Auth review', detail: 'Show MCP auth and quarantine attention without approving or changing trust.', command: '/mcp auth-review', kind: 'command', safety: 'read-only' },
      { id: 'secret-providers', label: 'Secret providers', detail: 'List supported external secret reference providers without printing secret values.', command: '/secrets providers', kind: 'command', safety: 'read-only' },
      { id: 'secret-list', label: 'Stored secrets', detail: 'List stored secret keys and refs without printing secret values.', command: '/secrets list', kind: 'command', safety: 'read-only' },
      { id: 'secret-set', label: 'Store secret value', detail: 'Open a masked, confirmed form that stores one secret value through the Agent secret manager.', editorKind: 'secret-set', kind: 'editor', safety: 'safe' },
      { id: 'secret-link', label: 'Link secret ref', detail: 'Open a confirmed form that links one key to a goodvibes://secrets/... external reference.', editorKind: 'secret-link', kind: 'editor', safety: 'safe' },
      { id: 'secret-test', label: 'Test secret ref', detail: 'Open a confirmed form that tests one secret reference while printing only redacted status.', editorKind: 'secret-test', kind: 'editor', safety: 'safe' },
      { id: 'secret-delete', label: 'Delete secret', detail: 'Open a confirmed form that deletes one stored secret key from the selected scope/storage.', editorKind: 'secret-delete', kind: 'editor', safety: 'safe' },
      { id: 'trust-review', label: 'Trust review', detail: 'Review permission, secret, plugin, and MCP trust posture without exporting bundles or changing trust.', command: '/trust review', kind: 'command', safety: 'read-only' },
      { id: 'trust-bundle-export', label: 'Export trust bundle', detail: 'Open a confirmed form that exports a redacted trust review bundle.', editorKind: 'trust-bundle-export', kind: 'editor', safety: 'safe' },
      { id: 'trust-bundle-inspect', label: 'Inspect trust bundle', detail: 'Open a form that inspects a trust review bundle before setup review.', editorKind: 'trust-bundle-inspect', kind: 'editor', safety: 'read-only' },
      { id: 'security-review', label: 'Security review', detail: 'Inspect token audit, MCP attack paths, policy lint, and plugin risk without mutating security state.', command: '/security review', kind: 'command', safety: 'read-only' },
      { id: 'mcp-settings', label: 'Settings workspace', detail: 'Open settings at the MCP section for deeper review, including allow-all decisions.', command: '/settings mcp', kind: 'command', safety: 'safe' },
      { id: 'mcp-safety', label: 'Tool safety', detail: 'Agent may inspect and add reviewed MCP servers by explicit command, but will not silently install packages, change trust, or expose tools from ordinary chat.', kind: 'guidance', safety: 'blocked' },
    ],
  },
  {
    id: 'knowledge',
    group: 'KNOW',
    label: 'Knowledge',
    summary: 'Agent Knowledge/Wiki and source-backed lookup.',
    detail: 'Agent knowledge calls use the isolated Agent Knowledge route family only. Default regular wiki and non-Agent knowledge segments are not the Agent knowledge environment.',
    actions: [
      { id: 'knowledge-status', label: 'Knowledge status', detail: 'Inspect Agent knowledge readiness and counts.', command: '/knowledge status', kind: 'command', safety: 'read-only' },
      { id: 'knowledge-search', label: 'Search Agent knowledge', detail: 'Open an in-workspace search form for the isolated Agent Knowledge index.', editorKind: 'knowledge-search', kind: 'editor', safety: 'read-only' },
      { id: 'knowledge-ingest-url', label: 'Ingest URL', detail: 'Open an in-workspace form that ingests a real URL into Agent Knowledge only after typed confirmation.', editorKind: 'knowledge-url', kind: 'editor', safety: 'safe' },
      { id: 'knowledge-import-urls', label: 'Import URL list', detail: 'Open an in-workspace form that imports a local URL list into Agent Knowledge only after typed confirmation.', editorKind: 'knowledge-urls', kind: 'editor', safety: 'safe' },
      { id: 'knowledge-ingest-file', label: 'Ingest file', detail: 'Open an in-workspace form that imports a local file into Agent Knowledge only after typed confirmation.', editorKind: 'knowledge-file', kind: 'editor', safety: 'safe' },
      { id: 'knowledge-import-bookmarks', label: 'Import bookmarks', detail: 'Open an in-workspace form that imports a browser bookmark export into Agent Knowledge after typed confirmation.', editorKind: 'knowledge-bookmarks', kind: 'editor', safety: 'safe' },
      { id: 'knowledge-import-browser-history', label: 'Import browser history', detail: 'Open an in-workspace form that imports local browser history/bookmarks into Agent Knowledge after typed confirmation.', editorKind: 'knowledge-browser-history', kind: 'editor', safety: 'safe' },
      { id: 'knowledge-ingest-connector', label: 'Ingest connector input', detail: 'Open an in-workspace form for explicit connector input after checking connector readiness.', editorKind: 'knowledge-connector-ingest', kind: 'editor', safety: 'safe' },
      { id: 'knowledge-review-queue', label: 'Review queue', detail: 'Inspect source, item, and issue review work before accepting, rejecting, or resolving anything.', command: '/knowledge queue', kind: 'command', safety: 'read-only' },
      { id: 'knowledge-sources', label: 'Source library', detail: 'List source-backed records already ingested into the isolated Agent Knowledge segment.', command: '/knowledge list --kind sources', kind: 'command', safety: 'read-only' },
      { id: 'knowledge-get', label: 'Show item', detail: 'Open an in-workspace form that shows one Agent Knowledge source, node, or issue by id.', editorKind: 'knowledge-get', kind: 'editor', safety: 'read-only' },
      { id: 'knowledge-review-issue', label: 'Review issue', detail: 'Open a confirmed form that accepts, rejects, resolves, reopens, edits, or forgets one Agent Knowledge issue.', editorKind: 'knowledge-review-issue', kind: 'editor', safety: 'safe' },
      { id: 'knowledge-candidates', label: 'Consolidation candidates', detail: 'Inspect Agent Knowledge consolidation candidates without running a consolidation job.', command: '/knowledge candidates', kind: 'command', safety: 'read-only' },
      { id: 'knowledge-lint', label: 'Knowledge lint', detail: 'Inspect Agent Knowledge lint findings.', command: '/knowledge lint', kind: 'command', safety: 'read-only' },
      { id: 'knowledge-reports', label: 'Knowledge reports', detail: 'Inspect recent Agent Knowledge reports without mutating knowledge.', command: '/knowledge reports', kind: 'command', safety: 'read-only' },
      { id: 'knowledge-schedules', label: 'Knowledge schedules', detail: 'Inspect Agent Knowledge report schedules without changing schedules.', command: '/knowledge schedules', kind: 'command', safety: 'read-only' },
      { id: 'knowledge-packet', label: 'Build prompt packet', detail: 'Open an in-workspace form that builds a compact Agent Knowledge prompt packet for a task.', editorKind: 'knowledge-packet', kind: 'editor', safety: 'read-only' },
      { id: 'knowledge-explain', label: 'Explain selection', detail: 'Open an in-workspace form that explains which Agent Knowledge context would be selected.', editorKind: 'knowledge-explain', kind: 'editor', safety: 'read-only' },
      { id: 'knowledge-consolidate', label: 'Consolidate knowledge', detail: 'Open a confirmed form that runs isolated Agent Knowledge consolidation.', editorKind: 'knowledge-consolidate', kind: 'editor', safety: 'safe' },
      { id: 'knowledge-reindex', label: 'Reindex Agent Knowledge', detail: 'Open a confirmed form that rebuilds the isolated Agent Knowledge index without touching default Knowledge/Wiki.', editorKind: 'knowledge-reindex', kind: 'editor', safety: 'safe' },
      { id: 'knowledge-ask', label: 'Ask Agent knowledge', detail: 'Open an in-workspace question form for isolated Agent Knowledge. Normal chat still uses the main conversation.', editorKind: 'knowledge-ask', kind: 'editor', safety: 'read-only' },
    ],
  },
  {
    id: 'voice-media',
    group: 'SETUP',
    label: 'Voice & Media',
    summary: 'Voice, TTS, image input, browser tools, and media providers.',
    detail: 'Voice, media, browser tools, and image-capable flows are first-class Agent tools. Service management stays outside Agent and side effects stay explicit.',
    actions: [
      { id: 'tts-config', label: 'Configure live TTS', detail: 'Open the settings workspace at the TTS group.', command: '/config tts', kind: 'command', safety: 'safe' },
      { id: 'tts-provider', label: 'Choose TTS provider', detail: 'Open provider/model routing for spoken responses through the settings flow.', command: '/config tts.provider', kind: 'command', safety: 'safe' },
      { id: 'voice-review', label: 'Voice review', detail: 'Inspect local voice posture before enabling spoken interaction.', command: '/voice review', kind: 'command', safety: 'read-only' },
      { id: 'voice-enable', label: 'Enable voice', detail: 'Open a confirmed form that enables local voice interaction.', editorKind: 'voice-enable', kind: 'editor', safety: 'safe' },
      { id: 'voice-disable', label: 'Disable voice', detail: 'Open a confirmed form that disables local voice interaction.', editorKind: 'voice-disable', kind: 'editor', safety: 'safe' },
      { id: 'voice-bundle-export', label: 'Export voice bundle', detail: 'Open a confirmed form that exports voice setup state for review.', editorKind: 'voice-bundle-export', kind: 'editor', safety: 'safe' },
      { id: 'voice-bundle-inspect', label: 'Inspect voice bundle', detail: 'Open a form that inspects voice setup state before review.', editorKind: 'voice-bundle-inspect', kind: 'editor', safety: 'read-only' },
      { id: 'tts-speak', label: 'Speak a prompt', detail: 'Open an in-workspace prompt form for spoken assistant replies through configured live TTS.', editorKind: 'tts-prompt', kind: 'editor', safety: 'safe' },
      { id: 'image-attach', label: 'Attach image input', detail: 'Open an in-workspace image form for attaching a real image path and optional prompt.', editorKind: 'image-input', kind: 'editor', safety: 'safe' },
      { id: 'browser-tools', label: 'Browser tools', detail: 'Inspect browser/tool server readiness without starting inbound endpoints or mutating connected-host state.', command: '/mcp servers', kind: 'command', safety: 'read-only' },
      { id: 'mcp-tools', label: 'MCP tool inventory', detail: 'List available MCP tools, including browser and automation roles, without changing server trust or setup.', command: '/mcp tools', kind: 'command', safety: 'read-only' },
    ],
  },
  {
    id: 'profiles',
    group: 'SETUP',
    label: 'Profiles',
    summary: 'Isolated Agent homes, starter templates, and setup bundles.',
    detail: 'Agent profiles isolate Agent state. Named homes and starter templates let one install behave like separate assistants for household, research, travel, operations, or personal workflows.',
    actions: [
      { id: 'runtime-profile-guide', label: 'Starter authoring guide', detail: 'Open the Agent-local starter authoring flow inside the Agent TUI.', command: '/agent-profile guide', kind: 'command', safety: 'safe' },
      { id: 'runtime-profile-templates', label: 'Browse starter templates', detail: 'List built-in and local Agent starter templates with persona, skill, routine, and source details.', command: '/agent-profile templates', kind: 'command', safety: 'read-only' },
      { id: 'runtime-profile-list', label: 'List Agent profiles', detail: 'List isolated Agent profile homes under this Agent home.', command: '/agent-profile list', kind: 'command', safety: 'read-only' },
      { id: 'runtime-profile-template-show', label: 'Preview starter', detail: 'Open an in-workspace form that previews one built-in or local starter template by id.', editorKind: 'profile-template-show', kind: 'editor', safety: 'read-only' },
      { id: 'runtime-profile-template-export', label: 'Export starter template', detail: 'Open an in-workspace form that exports a starter template JSON file for review and customization.', editorKind: 'profile-template-export', kind: 'editor', safety: 'safe' },
      { id: 'runtime-profile-template-import', label: 'Import starter template', detail: 'Open an in-workspace form that imports a reviewed starter template JSON file into this Agent home.', editorKind: 'profile-template-import', kind: 'editor', safety: 'safe' },
      { id: 'runtime-profile-create', label: 'Create Agent profile', detail: 'Open an in-workspace form that creates an isolated Agent home from a built-in or local starter.', editorKind: 'profile', kind: 'editor', safety: 'safe' },
      { id: 'runtime-profile-default', label: 'Use as default profile', detail: 'Select an isolated Agent profile for the next normal goodvibes-agent launch. The current session keeps using its existing Agent home.', editorKind: 'profile-default', kind: 'editor', safety: 'safe' },
      { id: 'runtime-profile-clear-default', label: 'Clear default profile', detail: 'Return the next normal goodvibes-agent launch to the base Agent home. The current session keeps using its existing Agent home.', editorKind: 'profile-default-clear', kind: 'editor', safety: 'safe' },
      { id: 'runtime-profile-delete', label: 'Delete Agent profile', detail: 'Open a confirmation form before deleting one isolated Agent profile home.', editorKind: 'profile-delete', kind: 'editor', safety: 'safe' },
      { id: 'runtime-profile-template-from-discovered', label: 'Starter from discovered behavior', detail: 'Open an in-workspace form that creates one local starter template from reviewed discovered persona, skill, and routine files.', editorKind: 'profile-template-from-discovered', kind: 'editor', safety: 'safe' },
      { id: 'runtime-profile-from-discovered', label: 'Profile from discovered behavior', detail: 'Open an in-workspace form that creates a local starter and isolated Agent profile from reviewed discovered behavior files.', editorKind: 'profile-from-discovered', kind: 'editor', safety: 'safe' },
      { id: 'runtime-profile-template-edit', label: 'Customize starter', detail: 'Open the starter export form, edit the JSON file, then import it as a local starter.', editorKind: 'profile-template-export', kind: 'editor', safety: 'safe' },
    ],
  },
  {
    id: 'memory',
    group: 'LEARN',
    label: 'Memory & Skills',
    summary: 'Local assistant memory, routines, skills, and reusable behavior.',
    detail: 'Memory, routines, skills, and personas stay Agent-local until stable shared registry contracts exist. Secrets must not be stored as memory.',
    actions: [
      { id: 'memory-list', label: 'List memory', detail: 'Print the full Agent-owned memory list.', command: '/memory list', kind: 'command', safety: 'read-only' },
      { id: 'memory-search', label: 'Search memory', detail: 'Open an in-workspace Agent-local memory search form. This never queries default Knowledge/Wiki or other product routes.', editorKind: 'memory-search', kind: 'editor', safety: 'read-only' },
      { id: 'memory-get', label: 'Show memory by id', detail: 'Open an in-workspace form that prints one Agent-local memory record with provenance and links.', editorKind: 'memory-get', kind: 'editor', safety: 'read-only' },
      { id: 'memory-queue', label: 'Review queue', detail: 'Print the Agent-local memory review queue.', command: '/memory queue', kind: 'command', safety: 'read-only' },
      { id: 'memory-explain', label: 'Explain selection', detail: 'Preview which reviewed Agent-local memories would be selected for a task.', editorKind: 'memory-explain', kind: 'editor', safety: 'read-only' },
      { id: 'memory-prev', label: 'Previous memory', detail: 'Move the local memory selection up without changing review state.', localKind: 'memory', selectionDelta: -1, kind: 'local-selection', safety: 'safe' },
      { id: 'memory-next', label: 'Next memory', detail: 'Move the local memory selection down without changing review state.', localKind: 'memory', selectionDelta: 1, kind: 'local-selection', safety: 'safe' },
      { id: 'memory-create', label: 'Create memory', detail: 'Open an in-workspace form for a durable, non-secret Agent memory. No default wiki fallback is used.', editorKind: 'memory', kind: 'editor', safety: 'safe' },
      { id: 'learned-behavior', label: 'Capture learned behavior', detail: 'Turn a reviewed workflow, lesson, or operating style into one local skill, routine, or persona.', editorKind: 'learned-behavior', kind: 'editor', safety: 'safe' },
      { id: 'memory-edit', label: 'Edit selected memory', detail: 'Open the selected Agent memory in an in-workspace editor.', localKind: 'memory', localOperation: 'memory-edit', kind: 'local-operation', safety: 'safe' },
      { id: 'memory-review', label: 'Review selected', detail: 'Mark the selected Agent memory reviewed after inspecting it.', localKind: 'memory', localOperation: 'memory-review', kind: 'local-operation', safety: 'safe' },
      { id: 'memory-stale', label: 'Mark selected stale', detail: 'Mark the selected Agent memory stale so it stops being trusted until reviewed.', localKind: 'memory', localOperation: 'memory-stale', kind: 'local-operation', safety: 'safe' },
      { id: 'memory-delete', label: 'Delete selected memory', detail: 'Open a confirmation form before deleting the selected Agent memory.', localKind: 'memory', localOperation: 'memory-delete', kind: 'local-operation', safety: 'safe' },
      { id: 'memory-promote', label: 'Promote memory', detail: 'Open a confirmed form that promotes one Agent-local memory record to session, project, or team scope.', editorKind: 'memory-promote', kind: 'editor', safety: 'safe' },
      { id: 'memory-link', label: 'Link memories', detail: 'Open a confirmed form that links two Agent-local memory records with a directed relation.', editorKind: 'memory-link', kind: 'editor', safety: 'safe' },
      { id: 'memory-export', label: 'Export memory bundle', detail: 'Open a confirmed form that exports Agent-local memory records and links to a reviewable JSON bundle.', editorKind: 'memory-export', kind: 'editor', safety: 'safe' },
      { id: 'memory-import', label: 'Import memory bundle', detail: 'Open a confirmed form that imports a reviewed Agent-local memory bundle.', editorKind: 'memory-import', kind: 'editor', safety: 'safe' },
      { id: 'memory-handoff-export', label: 'Export handoff bundle', detail: 'Open a confirmed form that exports a scoped Agent-local memory handoff bundle.', editorKind: 'memory-handoff-export', kind: 'editor', safety: 'safe' },
      { id: 'memory-handoff-inspect', label: 'Inspect handoff bundle', detail: 'Open a form that inspects a memory handoff bundle before import.', editorKind: 'memory-handoff-inspect', kind: 'editor', safety: 'read-only' },
      { id: 'memory-handoff-import', label: 'Import handoff bundle', detail: 'Open a confirmed form that imports a reviewed handoff bundle into Agent-local memory.', editorKind: 'memory-handoff-import', kind: 'editor', safety: 'safe' },
      { id: 'memory-vector-status', label: 'Vector status', detail: 'Inspect the Agent-local memory vector index status.', command: '/memory vector status', kind: 'command', safety: 'read-only' },
      { id: 'memory-vector-doctor', label: 'Vector doctor', detail: 'Inspect Agent-local memory vector index health.', command: '/memory vector doctor', kind: 'command', safety: 'read-only' },
      { id: 'memory-vector-rebuild', label: 'Rebuild vector index', detail: 'Open a confirmed form that rebuilds the Agent-local memory vector index.', editorKind: 'memory-vector-rebuild', kind: 'editor', safety: 'safe' },
      { id: 'personas', label: 'Persona library', detail: 'Open the local persona workspace for active role selection and review.', targetCategoryId: 'personas', kind: 'workspace', safety: 'safe' },
      { id: 'skills', label: 'Local skill library', detail: 'Open the local skill workspace for reusable procedures and review.', targetCategoryId: 'skills', kind: 'workspace', safety: 'safe' },
      { id: 'routines', label: 'Routine library', detail: 'Open the local routine workspace for repeatable workflows and schedule promotion review.', targetCategoryId: 'routines', kind: 'workspace', safety: 'safe' },
    ],
  },
  {
    id: 'personas',
    group: 'LEARN',
    label: 'Personas',
    summary: 'Local behavior profiles for the main assistant.',
    detail: 'Personas shape the serial Agent in the main conversation. They are local profiles and never spawn specialist roots.',
    actions: [
      { id: 'personas-list', label: 'List personas', detail: 'Print the full local persona library.', command: '/personas list', kind: 'command', safety: 'read-only' },
      { id: 'personas-active', label: 'Show active persona', detail: 'Inspect the active local persona applied to new turns.', command: '/personas active', kind: 'command', safety: 'read-only' },
      { id: 'personas-discover', label: 'Discover persona files', detail: 'Scan project and global Agent persona folders for persona markdown without importing it.', command: '/personas discover', kind: 'command', safety: 'read-only' },
      { id: 'personas-import-discovered', label: 'Import discovered persona', detail: 'Open an in-workspace form that imports one reviewed persona markdown file into the Agent-local persona registry after typed confirmation.', editorKind: 'persona-discovery-import', kind: 'editor', safety: 'safe' },
      { id: 'personas-prev', label: 'Previous persona', detail: 'Move the local persona selection up without changing active state.', localKind: 'persona', selectionDelta: -1, kind: 'local-selection', safety: 'safe' },
      { id: 'personas-next', label: 'Next persona', detail: 'Move the local persona selection down without changing active state.', localKind: 'persona', selectionDelta: 1, kind: 'local-selection', safety: 'safe' },
      { id: 'personas-create', label: 'Create persona', detail: 'Open an in-workspace form for a local persona that writes Agent-local state only.', editorKind: 'persona', kind: 'editor', safety: 'safe' },
      { id: 'personas-edit', label: 'Edit selected', detail: 'Open the selected local persona in an in-workspace editor.', localKind: 'persona', localOperation: 'persona-edit', kind: 'local-operation', safety: 'safe' },
      { id: 'personas-use', label: 'Use selected', detail: 'Activate the selected local persona for future main-conversation turns.', localKind: 'persona', localOperation: 'persona-use', kind: 'local-operation', safety: 'safe' },
      { id: 'personas-review', label: 'Review selected', detail: 'Mark the selected local persona reviewed after inspecting it.', localKind: 'persona', localOperation: 'persona-review', kind: 'local-operation', safety: 'safe' },
      { id: 'personas-clear', label: 'Clear active persona', detail: 'Return to the default Agent policy without deleting any persona.', localKind: 'persona', localOperation: 'persona-clear', kind: 'local-operation', safety: 'safe' },
      { id: 'personas-delete', label: 'Delete selected', detail: 'Open a confirmation form before deleting the selected local persona.', localKind: 'persona', localOperation: 'persona-delete', kind: 'local-operation', safety: 'safe' },
    ],
  },
  {
    id: 'skills',
    group: 'LEARN',
    label: 'Skills',
    summary: 'Reusable local procedures with setup readiness.',
    detail: 'Skills are local, reviewable procedures with optional env/command requirements. Enabled skills inform the main conversation; secret-looking content is rejected.',
    actions: [
      { id: 'skills-list', label: 'List skills', detail: 'Print the full local Agent skill library.', command: '/agent-skills list', kind: 'command', safety: 'read-only' },
      { id: 'skills-enabled', label: 'Enabled skills', detail: 'Show only skills currently injected into Agent guidance.', command: '/agent-skills enabled', kind: 'command', safety: 'read-only' },
      { id: 'skills-attention', label: 'Needs setup', detail: 'Show local skills whose env or command requirements are not ready.', command: '/agent-skills attention', kind: 'command', safety: 'read-only' },
      { id: 'skills-discover', label: 'Discover skill files', detail: 'Scan project and global Agent skill folders for SKILL.md or .md skills without importing them.', command: '/agent-skills discover', kind: 'command', safety: 'read-only' },
      { id: 'skills-import-discovered', label: 'Import discovered skill', detail: 'Open an in-workspace form that imports one reviewed discovered skill file into the Agent-local skill registry after typed confirmation.', editorKind: 'skill-discovery-import', kind: 'editor', safety: 'safe' },
      { id: 'skills-bundles', label: 'Skill bundles', detail: 'List reviewable groups of local skills that can be enabled together.', command: '/agent-skills bundle list', kind: 'command', safety: 'read-only' },
      { id: 'skills-bundle-attention', label: 'Bundle setup gaps', detail: 'Show skill bundles whose member skills have missing env or command requirements.', command: '/agent-skills bundle attention', kind: 'command', safety: 'read-only' },
      { id: 'skills-create-bundle', label: 'Create bundle', detail: 'Open an in-workspace form that creates a named skill bundle from existing local skill ids.', editorKind: 'skill-bundle', kind: 'editor', safety: 'safe' },
      { id: 'skills-search-bundle', label: 'Search bundles', detail: 'Open an in-workspace form that searches local Agent skill bundles.', editorKind: 'skill-bundle-search', kind: 'editor', safety: 'read-only' },
      { id: 'skills-show-bundle', label: 'Show bundle', detail: 'Open an in-workspace form that shows one local Agent skill bundle by id.', editorKind: 'skill-bundle-show', kind: 'editor', safety: 'read-only' },
      { id: 'skills-update-bundle', label: 'Update bundle', detail: 'Open a confirmed form that updates one local Agent skill bundle.', editorKind: 'skill-bundle-update', kind: 'editor', safety: 'safe' },
      { id: 'skills-enable-bundle', label: 'Enable bundle', detail: 'Open a confirmed form that enables one local Agent skill bundle for main-conversation guidance.', editorKind: 'skill-bundle-enable', kind: 'editor', safety: 'safe' },
      { id: 'skills-disable-bundle', label: 'Disable bundle', detail: 'Open a confirmed form that disables one local Agent skill bundle without deleting it.', editorKind: 'skill-bundle-disable', kind: 'editor', safety: 'safe' },
      { id: 'skills-review-bundle', label: 'Review bundle', detail: 'Open a confirmed form that marks one local Agent skill bundle reviewed.', editorKind: 'skill-bundle-review', kind: 'editor', safety: 'safe' },
      { id: 'skills-stale-bundle', label: 'Mark bundle stale', detail: 'Open a confirmed form that marks one local Agent skill bundle stale with a reason.', editorKind: 'skill-bundle-stale', kind: 'editor', safety: 'safe' },
      { id: 'skills-delete-bundle', label: 'Delete bundle', detail: 'Open a confirmation form before deleting one local Agent skill bundle.', editorKind: 'skill-bundle-delete', kind: 'editor', safety: 'safe' },
      { id: 'skills-prev', label: 'Previous skill', detail: 'Move the local skill selection up without changing enabled state.', localKind: 'skill', selectionDelta: -1, kind: 'local-selection', safety: 'safe' },
      { id: 'skills-next', label: 'Next skill', detail: 'Move the local skill selection down without changing enabled state.', localKind: 'skill', selectionDelta: 1, kind: 'local-selection', safety: 'safe' },
      { id: 'skills-create', label: 'Create skill', detail: 'Open an in-workspace form for a reusable local procedure that writes Agent-local state only.', editorKind: 'skill', kind: 'editor', safety: 'safe' },
      { id: 'skills-edit', label: 'Edit selected', detail: 'Open the selected local Agent skill in an in-workspace editor.', localKind: 'skill', localOperation: 'skill-edit', kind: 'local-operation', safety: 'safe' },
      { id: 'skills-enable', label: 'Enable selected', detail: 'Enable the selected local Agent skill for future main-conversation guidance.', localKind: 'skill', localOperation: 'skill-enable', kind: 'local-operation', safety: 'safe' },
      { id: 'skills-disable', label: 'Disable selected', detail: 'Disable the selected local Agent skill without deleting it.', localKind: 'skill', localOperation: 'skill-disable', kind: 'local-operation', safety: 'safe' },
      { id: 'skills-review', label: 'Review selected', detail: 'Mark the selected local skill reviewed after inspecting it.', localKind: 'skill', localOperation: 'skill-review', kind: 'local-operation', safety: 'safe' },
      { id: 'skills-delete', label: 'Delete selected', detail: 'Open a confirmation form before deleting the selected local Agent skill.', localKind: 'skill', localOperation: 'skill-delete', kind: 'local-operation', safety: 'safe' },
    ],
  },
  {
    id: 'routines',
    group: 'LEARN',
    label: 'Routines',
    summary: 'Repeatable workflows with setup readiness.',
    detail: 'Routines run in the main conversation by default and can declare env/command requirements. Promotion to a connected schedule requires a real schedule command and --yes.',
    actions: [
      { id: 'routines-list', label: 'List routines', detail: 'Print the full local Agent routine library.', command: '/routines list', kind: 'command', safety: 'read-only' },
      { id: 'routines-enabled', label: 'Enabled routines', detail: 'Show routines available for direct use.', command: '/routines enabled', kind: 'command', safety: 'read-only' },
      { id: 'routines-attention', label: 'Needs setup', detail: 'Show local routines whose env or command requirements are not ready.', command: '/routines attention', kind: 'command', safety: 'read-only' },
      { id: 'routines-discover', label: 'Discover routine files', detail: 'Scan project and global Agent routine folders for routine markdown without importing it.', command: '/routines discover', kind: 'command', safety: 'read-only' },
      { id: 'routines-import-discovered', label: 'Import discovered routine', detail: 'Open an in-workspace form that imports one reviewed routine markdown file into the Agent-local routine registry after typed confirmation.', editorKind: 'routine-discovery-import', kind: 'editor', safety: 'safe' },
      { id: 'routines-prev', label: 'Previous routine', detail: 'Move the local routine selection up without changing enabled state.', localKind: 'routine', selectionDelta: -1, kind: 'local-selection', safety: 'safe' },
      { id: 'routines-next', label: 'Next routine', detail: 'Move the local routine selection down without changing enabled state.', localKind: 'routine', selectionDelta: 1, kind: 'local-selection', safety: 'safe' },
      { id: 'routines-create', label: 'Create routine', detail: 'Open an in-workspace form for a repeatable local workflow that writes Agent-local state only.', editorKind: 'routine', kind: 'editor', safety: 'safe' },
      { id: 'routines-edit', label: 'Edit selected', detail: 'Open the selected local Agent routine in an in-workspace editor.', localKind: 'routine', localOperation: 'routine-edit', kind: 'local-operation', safety: 'safe' },
      { id: 'routines-start', label: 'Start selected', detail: 'Mark the selected routine started and show it as a main-conversation workflow. This creates no hidden job.', localKind: 'routine', localOperation: 'routine-start', kind: 'local-operation', safety: 'safe' },
      { id: 'routines-enable', label: 'Enable selected', detail: 'Enable the selected routine for future main-conversation guidance.', localKind: 'routine', localOperation: 'routine-enable', kind: 'local-operation', safety: 'safe' },
      { id: 'routines-disable', label: 'Disable selected', detail: 'Disable the selected routine without deleting it.', localKind: 'routine', localOperation: 'routine-disable', kind: 'local-operation', safety: 'safe' },
      { id: 'routines-review', label: 'Review selected', detail: 'Mark the selected local routine reviewed after inspecting it.', localKind: 'routine', localOperation: 'routine-review', kind: 'local-operation', safety: 'safe' },
      { id: 'routines-delete', label: 'Delete selected', detail: 'Open a confirmation form before deleting the selected local Agent routine.', localKind: 'routine', localOperation: 'routine-delete', kind: 'local-operation', safety: 'safe' },
      { id: 'routines-promote', label: 'Promote to schedule', detail: 'Open an in-workspace form that creates one connected schedule from the selected routine with real timing and confirmation.', editorKind: 'routine-schedule', kind: 'editor', safety: 'safe' },
      { id: 'routines-receipts', label: 'Promotion receipts', detail: 'Inspect local redacted routine schedule promotion receipts.', command: '/routines receipts', kind: 'command', safety: 'read-only' },
    ],
  },
  {
    id: 'work',
    group: 'TRACK',
    label: 'Work & Approvals',
    summary: 'Visible task state, work plan, and approval posture.',
    detail: 'Use this workspace to inspect active operator state and update visible work-plan items from confirmed TUI forms.',
    actions: [
      { id: 'workplan', label: 'Review work plan', detail: 'Print a concise work plan summary in the main Agent transcript.', command: '/workplan list', kind: 'command', safety: 'read-only' },
      { id: 'workplan-add', label: 'Add work item', detail: 'Open a form that creates one visible work plan item from the Agent workspace.', editorKind: 'workplan-add', kind: 'editor', safety: 'safe' },
      { id: 'workplan-status', label: 'Update work item status', detail: 'Open a form that updates one work plan item to pending, active, blocked, done, failed, or cancelled.', editorKind: 'workplan-status', kind: 'editor', safety: 'safe' },
      { id: 'workplan-delete', label: 'Remove work item', detail: 'Open a confirmed form before removing one work plan item.', editorKind: 'workplan-delete', kind: 'editor', safety: 'safe' },
      { id: 'workplan-clear-completed', label: 'Clear completed work', detail: 'Open a confirmed form before clearing completed and cancelled work plan items.', editorKind: 'workplan-clear-completed', kind: 'editor', safety: 'safe' },
      { id: 'conversation-export', label: 'Export conversation', detail: 'Open a confirmed form that exports the current Agent conversation to a workspace file.', editorKind: 'conversation-export', kind: 'editor', safety: 'safe' },
      { id: 'session-save', label: 'Save session', detail: 'Open a confirmed form that saves the current Agent session under a local name.', editorKind: 'session-save', kind: 'editor', safety: 'safe' },
      { id: 'session-load', label: 'Load session', detail: 'Open a confirmed form that loads one saved Agent session into the current conversation.', editorKind: 'session-load', kind: 'editor', safety: 'safe' },
      { id: 'session-rename', label: 'Rename current session', detail: 'Open a form that renames the current Agent session.', editorKind: 'session-rename', kind: 'editor', safety: 'safe' },
      { id: 'session-resume', label: 'Resume saved session', detail: 'Open a form that resumes one saved Agent session by id, prefix, or title.', editorKind: 'session-resume', kind: 'editor', safety: 'safe' },
      { id: 'session-info', label: 'Inspect saved session', detail: 'Open a read-only form that prints saved-session metadata.', editorKind: 'session-info', kind: 'editor', safety: 'read-only' },
      { id: 'session-export-saved', label: 'Export saved session', detail: 'Open a form that prints one saved-session transcript as markdown or text.', editorKind: 'session-export-saved', kind: 'editor', safety: 'read-only' },
      { id: 'session-search', label: 'Search saved sessions', detail: 'Open a form that searches saved Agent sessions.', editorKind: 'session-search', kind: 'editor', safety: 'read-only' },
      { id: 'session-delete', label: 'Delete saved session', detail: 'Open a confirmed form before deleting one saved Agent session.', editorKind: 'session-delete', kind: 'editor', safety: 'safe' },
      { id: 'planning-status', label: 'Planning status', detail: 'Inspect current Agent planning readiness, mode, and next question without seeding or approving planning state.', command: '/plan status', kind: 'command', safety: 'read-only' },
      { id: 'planning-list', label: 'Saved plans', detail: 'List local execution plans without opening copied planning panels or changing planning state.', command: '/plan list', kind: 'command', safety: 'read-only' },
      { id: 'tasks-list', label: 'Runtime tasks', detail: 'Inspect connected-host task state without creating, retrying, or mutating tasks.', command: '/tasks list', kind: 'command', safety: 'read-only' },
      { id: 'sessions-list', label: 'Saved sessions', detail: 'Browse saved Agent sessions from the TUI without using a shell-only command.', command: '/sessions', kind: 'command', safety: 'read-only' },
      { id: 'approvals', label: 'Review approvals', detail: 'Print the approval matrix without approving or denying requests.', command: '/approval matrix', kind: 'command', safety: 'read-only' },
    ],
  },
  {
    id: 'automation',
    group: 'WATCH',
    label: 'Automation',
    summary: 'Reminders, schedule observability, and explicit routine promotion.',
    detail: 'Agent does not create local automation jobs or hidden scheduler spawns. Confirmed reminders and reviewed local routines can create connected schedules through explicit schedules.create commands with --yes.',
    actions: [
      { id: 'schedule-reminder', label: 'Create reminder', detail: 'Open an in-workspace form that creates one connected reminder schedule with real timing, optional delivery target, and explicit confirmation.', editorKind: 'reminder-schedule', kind: 'editor', safety: 'safe' },
      { id: 'schedule-list', label: 'List schedules', detail: 'Inspect configured jobs and history without running or mutating them.', command: '/schedule list', kind: 'command', safety: 'read-only' },
      { id: 'schedule-promote-routine', label: 'Promote routine', detail: 'Open an in-workspace form that creates one connected schedule from a local Agent routine with real timing, optional delivery target, and explicit confirmation.', editorKind: 'routine-schedule', kind: 'editor', safety: 'safe' },
      { id: 'schedule-receipts', label: 'Promotion receipts', detail: 'Review local redacted receipt history for routine-to-schedule promotion attempts.', command: '/schedule receipts', kind: 'command', safety: 'read-only' },
      { id: 'schedule-reconcile', label: 'Reconcile schedules', detail: 'Compare local promotion receipts with live connected schedules using schedules.list.', command: '/schedule reconcile', kind: 'command', safety: 'read-only' },
      { id: 'schedule-policy', label: 'Local scheduler blocked', detail: 'Local schedule add/run/remove/enable/disable remain blocked; confirmed reminders and routine promotion use connected schedules only.', kind: 'guidance', safety: 'blocked' },
      { id: 'health-services', label: 'Host status', detail: 'Inspect connected-host readiness without starting, stopping, or restarting anything.', command: '/health review', kind: 'command', safety: 'read-only' },
    ],
  },
  {
    id: 'delegate',
    group: 'BUILD',
    label: 'Build Delegation',
    summary: 'Explicit handoff to GoodVibes TUI for code work.',
    detail: 'Agent does not become the coding TUI. Build, implement, fix, patch, and review work must be handed to GoodVibes TUI with the full original ask and WRFC only when explicitly requested.',
    actions: [
      { id: 'delegate-guidance', label: 'Delegation rule', detail: 'For build/fix/review work, delegate one request to GoodVibes TUI instead of spawning local Engineer/Reviewer/Tester roots.', kind: 'guidance', safety: 'delegates' },
      { id: 'delegate-task', label: 'Delegate build task', detail: 'Open a confirmed form that sends one explicit build/fix/review task to GoodVibes TUI/shared-session routes.', editorKind: 'delegate-task', kind: 'editor', safety: 'delegates' },
      { id: 'review-command', label: 'Review delegation command', detail: 'Use /delegate --wrfc TASK only when the user explicitly asks for code review/build execution. Return to the composer and include the actual task text.', kind: 'guidance', safety: 'delegates' },
      { id: 'delegation-status', label: 'Delegation status', detail: 'Inspect build-delegation receipts and shared-session status without starting coding work.', command: '/delegate status', kind: 'command', safety: 'read-only' },
    ],
  },
];
