import type { ToolRegistry } from '@pellux/goodvibes-sdk/platform/tools';
import type { CommandContext, CommandRegistry } from '../input/command-registry.ts';

export interface AgentHarnessToolArgs {
  readonly mode?: unknown;
  readonly query?: unknown;
  readonly command?: unknown;
  readonly cliCommand?: unknown;
  readonly commandName?: unknown;
  readonly args?: unknown;
  readonly channelId?: unknown;
  readonly notificationTargetId?: unknown;
  readonly providerId?: unknown;
  readonly mcpServerId?: unknown;
  readonly setupItemId?: unknown;
  readonly contextFileId?: unknown;
  readonly receiptId?: unknown;
  readonly turnId?: unknown;
  readonly outcomeStatus?: unknown;
  readonly modelRouteId?: unknown;
  readonly executionRouteId?: unknown;
  readonly executionRecordId?: unknown;
  readonly processId?: unknown;
  readonly processSessionId?: unknown;
  readonly processAction?: unknown;
  readonly action?: unknown;
  readonly recoveryAction?: unknown;
  readonly laneId?: unknown;
  readonly queueItemId?: unknown;
  readonly candidateId?: unknown;
  readonly sourceId?: unknown;
  readonly runId?: unknown;
  readonly pairingRouteId?: unknown;
  readonly delegationRouteId?: unknown;
  readonly findingId?: unknown;
  readonly bundlePath?: unknown;
  readonly mediaProviderId?: unknown;
  readonly sessionId?: unknown;
  readonly session_id?: unknown;
  readonly categoryId?: unknown;
  readonly panelId?: unknown;
  readonly actionId?: unknown;
  readonly recordId?: unknown;
  readonly fields?: unknown;
  readonly combo?: unknown;
  readonly combos?: unknown;
  readonly surfaceId?: unknown;
  readonly key?: unknown;
  readonly value?: unknown;
  readonly cwd?: unknown;
  readonly timeoutMs?: unknown;
  readonly pty?: unknown;
  readonly data?: unknown;
  readonly target?: unknown;
  readonly artifactId?: unknown;
  readonly itemId?: unknown;
  readonly methodId?: unknown;
  readonly endpointId?: unknown;
  readonly capabilityId?: unknown;
  readonly toolName?: unknown;
  readonly tool?: unknown;
  readonly toolArgs?: unknown;
  readonly agentId?: unknown;
  readonly category?: unknown;
  readonly prefix?: unknown;
  readonly includeHidden?: unknown;
  readonly includeParameters?: unknown;
  readonly limit?: unknown;
  readonly pane?: unknown;
  readonly confirm?: unknown;
  readonly explicitUserRequest?: unknown;
}

export interface AgentHarnessToolDeps {
  readonly commandRegistry: CommandRegistry;
  readonly commandContext: CommandContext;
  readonly toolRegistry: ToolRegistry;
}
